project:
  type: website

website:
  title: "AI Shares"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: sources.qmd
        text: Sources

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

